#!/bin/bash

usage () {
	echo "$PROGNAME: usage: $PROGNAME [-f file | -i]"
	return
}

# process command line options

interactive=
filename=

echo "Num arguments: $#"

while [[ -n "$1" ]]; do
	case "$1" in
		-f | --file)		shift # the next argument is the file name
					filename="$1"
					;;
		-i | --interactive)	interactive=1
					;;
		-h | --help)		usage
					exit
					;;
		*)			usage >&2
					exit 1
					;;
	esac
	shift
done

# interactive mode 

if [[ -n "$interactive" ]]; then
	while true; do
		read -p "Enter name of output file: " filename
		if [[ -e "$filename" ]]; then
			read -p "'$filename' exists. Overwrite? [y/n/q] > "
			case "$REPLY" in
				Y|y|yes) 	break # todo stuff
						;;
				Q|q|N|n|No)	echo "Program terminated."
						exit
						;;
				*)		continue
						;;
			esac
		elif [[ -z "$filename" ]]; then
			continue # keep going until a filename is given
		else
			break
		fi
	done
fi

echo "Interactive: $interactive"
echo "Filename: $filename"

# output html page

write_html_page() {
	cat <<- _EOF_
	<html>
		<head>
			<title>$TITLE</title>
		</head>
		<body>
			<h1>$TITLE</title>
			<p>$TIMESTAMP</p>
			$(report_uptime)
			$(report_disk_space)
			$(report_home_space)
		</body>
	</html>
	_EOF_
	return
}

report_uptime() {
	echo "not yet implemented"
	return
}

report_disk_space() {
	echo "not yet implemented"
	return
}

report_home_space() {
	echo "not yet implemented"
	return
}

if [[ -n "$filename" ]]; then
	if touch "$filename" && [[ -f "$filename" ]]; then # touch handles invalid pathnames
		write_html_page > "$filename"
	else
		echo "$PROGNAME: Cannot write file '$filename'" >&2
		exit 1
	fi
else
	write_html_page
fi
