#!/bin/bash

# Program to output a system information page
# make executable via chmod 755 /path/to/file
# store in ~/bin to have it auto-added to path on an ubuntu system

TITLE="System Information Report For $HOSTNAME"
CURRENT_TIME="$(date +"%x %r %Z")"
TIMESTAMP="Generated $CURRENT_TIME, by <a href="https://www.github.com/eqmvii">$USER</a>."

report_uptime () {
  return
}

report_disk_space () {
  return
}

report_home_space () {
  return
}

get_current_git_sha () {
  echo "SHA: $(git rev-parse HEAD)"
  return
}

cat <<- _EOF_
  <html>
    <head>
      <title>$TITLE</title>
    </head>
    <body>
      <h1>$TITLE</h1>
      <p>$TIMESTAMP</p>
      </hr />
      $(report_uptime)
      $(report_disk_space)
      $(report_home_space)
      $(get_current_git_sha)
    </body>
  </html>
_EOF_

# Written entirely in vim! woah!
